apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddvpn-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddvpn-telegram-bot
  template:
    metadata:
      labels:
        app: ddvpn-telegram-bot
    spec:
      containers:
        - name: ddvpn-telegram-bot
          image: ddvpn-telegram-bot-bot
          command: ['python', 'main.py']
          envFrom:
            - secretRef:
                name: telegram-db-secret
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ddvpn-telegram-bot-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ddvpn-telegram-bot-db
  template:
    metadata:
      labels:
        app: ddvpn-telegram-bot-db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: telegram-db-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ddvpn-telegram-bot-service
spec:
  selector:
    app: ddvpn-telegram-bot
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ddvpn-telegram-bot-db
spec:
  selector:
    app: ddvpn-telegram-bot-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
