apiVersion: apps/v1
kind: Deployment
metadata:
  name: marzban
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marzban
  template:
    metadata:
      labels:
        app: marzban
    spec:
      containers:
        - name: marzban
          image: gozargah/marzban:latest
          command:
            [
              'bash',
              '-c',
              'alembic upgrade head && uvicorn app:app --host 0.0.0.0 --port 8000',
            ]
          envFrom:
            - secretRef:
                name: telegram-db-secret
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: marzban-service
spec:
  selector:
    app: marzban
  ports:
    - port: 8000
      targetPort: 8000
