apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: marzban-node-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marzban-node-monitor
  template:
    metadata:
      labels:
        app: marzban-node-monitor
    spec:
      containers:
        - name: marzban-node-monitor
          image: sm1kyx/marzban-node-monitor:latest
          command: ['python', 'main.py']
          envFrom:
            - secretRef:
                name: monitor-redis-secret
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: marzban-node-monitor-service
spec:
  selector:
    app: marzban-node-monitor
  ports:
    - port: 8081
      targetPort: 8081
